name: Build and deploy Node.js app to Azure Web App - dev-heartstore


# Triggers when code is pushed to the master branch
on:
  push:
    branches:
      - main

# List of tasks that happen during the workflow
jobs:
  build-and-deploy:
    runs-on: windows-latest

# Fetches the repo
    steps:
    - uses: actions/checkout@master

# Checks the node.js version
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

# Runs npm install and npm run build+test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

# Deploys the code to the Azure web app
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-heartstore'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b490fc7656ce41eca39835e8fb26a416 }}
        package: .